name: Release Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install musl-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/github-db
          mv target/x86_64-unknown-linux-musl/release/github-db github-db-linux-x86_64

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            github-db-linux-x86_64
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  template:
    name: Update Template Repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/github-db-template
          token: ${{ secrets.TEMPLATE_TOKEN }}

      - name: Update Template
        run: |
          # Update workflow to use the new release
          sed -i "s|github-db/releases/.*download/|github-db/releases/download/${{ github.ref_name }}/|" .github/workflows/database.yml
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .github/workflows/database.yml
          git commit -m "Update to release ${{ github.ref_name }}" || echo "No changes to commit"
          git push
